#!/usr/bin/env python3
"""Converts an image into the firmware's embedded sleep-screen cover bitmap.

The X3 panel is 792x528 physically (landscape controller) but the firmware
runs it in Portrait, so the logical/on-screen resolution is 528x792 -- that's
the size this script emits. Any input image (PNG/JPEG/etc, any size) is
resized to fit, converted to grayscale, and thresholded to 1-bit: pixels
darker than --threshold become ink (drawn black), everything else is left as
the screen's white background.

Output is a C++ header with the bitmap packed row-major, MSB-first, one bit
per pixel (freeink's BW1 format) as a flash-resident array -- no SD card or
runtime heap needed to show it.

Usage:
  uv run --with pillow tools/img_to_bitmap.py cover.png -o src/cover_bitmap.h
"""
import argparse

from PIL import Image, ImageOps

WIDTH = 528
HEIGHT = 792


def convert(image_path: str, threshold: int) -> bytearray:
    img = Image.open(image_path).convert("L")
    if img.size != (WIDTH, HEIGHT):
        img = ImageOps.pad(img, (WIDTH, HEIGHT), color=255, centering=(0.5, 0.5))

    row_bytes = (WIDTH + 7) // 8
    data = bytearray(row_bytes * HEIGHT)
    px = img.load()
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if px[x, y] < threshold:
                data[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
    return data


def write_header(data: bytearray, out_path: str, source_name: str) -> None:
    with open(out_path, "w") as f:
        f.write("// Generated by tools/img_to_bitmap.py from " + source_name + " -- do not edit by hand.\n")
        f.write("// Regenerate: uv run --with pillow tools/img_to_bitmap.py <image> -o " + out_path + "\n")
        f.write("#pragma once\n\n#include <cstdint>\n\n")
        f.write(f"constexpr uint16_t kCoverBitmapWidth = {WIDTH};\n")
        f.write(f"constexpr uint16_t kCoverBitmapHeight = {HEIGHT};\n")
        f.write(f"constexpr uint32_t kCoverBitmapBytes = {len(data)};\n")
        f.write("constexpr uint8_t kCoverBitmapData[kCoverBitmapBytes] = {\n")
        for i in range(0, len(data), 20):
            f.write("    " + ", ".join(str(b) for b in data[i:i + 20]) + ",\n")
        f.write("};\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image", help="source image, any size/format Pillow can read")
    ap.add_argument("-o", "--out", default="src/cover_bitmap.h", help="output header path")
    ap.add_argument("--threshold", type=int, default=128, help="0-255 gray level below which a pixel is ink")
    args = ap.parse_args()

    data = convert(args.image, args.threshold)
    write_header(data, args.out, args.image)
    print(f"wrote {args.out}: {WIDTH}x{HEIGHT}, {len(data)} bytes")


if __name__ == "__main__":
    main()
